//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary_NBA_IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public int Author_ID { get; set; }
        public string Name { get; set; }
        public string Bio { get; set; }
        public string Book_ID { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
