//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary_NBA_IT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Digital_library_DBEntities : DbContext
    {
        public Digital_library_DBEntities()
            : base("name=Digital_library_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<CART> CART { get; set; }
        public virtual DbSet<WAITLIST> WAITLIST { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
