//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary_NBA_IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public string Book_ID { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Feedback { get; set; }
        public System.DateTime ReviewDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
