//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary_NBA_IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteFeedback
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> Stars { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
