//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary_NBA_IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLibrary
    {
        public int ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Book_ID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public bool IsBorrowed { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool ReminderSent { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
