//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary_NBA_IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAITLIST
    {
        public int waitlist_id { get; set; }
        public int user_id { get; set; }
        public object User_ID { get; internal set; }
        public string book_id { get; set; }
        public string Book_ID { get; internal set; }
        public int position { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        public virtual Books Books { get; set; }
        public object DateAdded { get; internal set; }
    }
}
